builds:
  - main: ./tinyport/cmd/tinyport
    ldflags:
      - -s -w -X github.com/notional-labs/tinyport/tinyport/internal/version.Version={{.Tag}} -X github.com/notional-labs/tinyport/tinyport/internal/version.Date={{.Date}} -X github.com/notional-labs/tinyport/tinyport/internal/version.Head={{.FullCommit}}
    goarch:
      - amd64
