#!/bin/bash

# generates static Go files to embed node cli programs into Tinyport for linux and darwin.

set -e

cd ./scripts/data/gen-nodetime

npm i 
npm run build

tar -czvf nodetime-linux-amd64.tar.gz nodetime-linux
tar -czvf nodetime-darwin-amd64.tar.gz nodetime-macos

mv nodetime-*.tar.gz ../../../tinyport/pkg/nodetime/data

rm nodetime-linux nodetime-macos
rm -rf dist/
